### PR TITLE
Feat/clone dataset

### PR DESCRIPTION
**Pull request by segments-tobias**

### CODE REVIEW

**Comment by segments-tobias** [comment]
@segments-arnout Not sure why the tests are failing

**Comment by segments-arnout** [comment]
You can run "make format" and push again to fix the error (black and isort checks failed). I can maybe change that we don't check for black and isort but actively run it on push.

**Comment by segments-tobias** [comment]
image
Formatting seems fine on my end

**Comment by segments-arnout** [comment]
Will look into it.

**Pull request merged**
