### PR TITLE
fix: add default ego pose for merged point cloud mode

### PR DESCRIPTION
**Pull request by segments-arnaud**

### CODE REVIEW

**Comment by segments-tobias** [comment]
Doesn't this add unnecessary load to our tiling pipeline by merging point clouds when the users has no ego poses?

**Comment by segments-arnaud** [comment]
Yes it adds load on a server (but takes load of a human - you can't forget it). Depends on what you find unnecessary 😄 

+ It does tiling by default with this PR enabled so you better discover the tiling feature. 

Is tiling a heavy operation?

**Comment by segments-tobias** [comment]
The thing is that tiling the individual frames happens automatically even if there are no ego poses. 
The only thing this PR does is force the merged point cloud, even when the user doesn't have ego poses.

**Comment by dbbert** [comment]
> Maybe a better solution is to show the merged point cloud button greyed out (when you didn't upload ego poses) with a popup message on hover saying 'Upload ego poses to use the merged point cloud mode. For more information about ego poses please have a look at the [docs](https://github.com/segments-ai/segments-ai/pull/...)')

Yes I like this better too. (Sorry for late reply, only seeing this now)

**Pull request closed without merging**
